CREATE TABLE MESSEAGE_TABLE (
		PAGE_ID INTEGER NOT NULL,
		LANGUAGE_CODE CHAR(5) NOT NULL,
		MESSEAGE_TEXT VARCHAR(512) NOT NULL
	);

CREATE UNIQUE INDEX SQL140702232732700 ON MESSEAGE_TABLE (PAGE_ID ASC, LANGUAGE_CODE ASC);

ALTER TABLE MESSEAGE_TABLE ADD CONSTRAINT MESSEAGE_TABLE_PRIMARY1 PRIMARY KEY (PAGE_ID, LANGUAGE_CODE);